# Generated by Django 4.1.1 on 2022-12-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_author_user_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='small_description',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
